// <auto-generated />
namespace TMSWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202104021702221_addfield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
